name: Build and publish release binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist
          output=remake_${{ matrix.goos }}_${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then output=$output.exe; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags "-s -w -X github.com/TrianaLab/remake/config.buildVersion=${{ github.event.release.tag_name }}" \
            -o dist/$output .

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.event.release.tag_name, 'v')
        with:
          files: dist/remake_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
